### ISSUE TITLE
Bug in navScroll navHeight: 0

### ISSUE THREAD

**Issue by leolux** [jhammann/jquery-navScroll#1]
The demo http://jhammann.github.io/jquery-navScroll/demo/ containes a button called "click-me" which should scroll to page up to section 1. But it does not scroll up completely. Only clicking the menu item "Section 1" works fine.

The following code does not work as expected:

```
$('.click-me').navScroll({
    navHeight: 0
});
```

**Comment by jhammann** [comment]
It's a demo example to show you can attach navScroll to any element for it to scroll to a section. As you can read in the demo the navHeight is set to 0 on purpose.

**Comment by leolux** [comment]
Alright, I got it. 
Thanks!
