### ISSUE TITLE
Feature to dismiss the menu with a click outside

### ISSUE THREAD

**Issue by leolux** [jhammann/jquery-navScroll#2]
There are three possible ways to close the menu but there are only 2 ways implemented currently.
I suggest to add a configuration option to enable another click listener which would close the menu when the user clicks outside the menu somewhere on the page.

**Comment by jhammann** [comment]
That's not really a feature for this plugin. The menu is only hidden if you click a navigation item. That's because this plugin handles clicking within the navigation. Clicking outside of the navigation is outside of this plugin's scope.

**Comment by leolux** [comment]
I totally agree. It is easy to implemented this feature by myself. 
Most importantly any overenigeering is prone to introduce problems.
