### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by leolux** [jhammann/jquery-navScroll#3]
Error occurs in the lastest version in line 123:

```
if (scrollPos > (item.offset().top - changeBounds)) {
```

**Comment by jhammann** [comment]
Can you share your markup and navScroll implementation? It would help me to recreate this issue and fix it.

**Comment by leolux** [comment]
I can't reproduce it either but I don't know why it works at the moment. Therefore I have to close this issue.
